name: ci-pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use node.js v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Commitlint
        run: npx commitlint -f origin/$GITHUB_BASE_REF -t origin/$GITHUB_HEAD_REF

      - name: Lint
        run: make lint

      - name: Unit Test
        run: make test
###### disabling the e2e tests until bootstrap can run in the pipeline. the tests expect data in strapi
#      - name: Start
#        run: make ci-start
#
#      - name: E2E Test
#        run: make e2e
#        env:
#          # don't worry, these are for local only
#          APP_KEYS: "G6+MKa9wMuIrvrEOIJWOGQ==,tfjbsIf+LWqYzNQqlAGfPA==,zpaXHqxzijZ6hFBE64HVDA==,z46v4mnd0Q9LNk1/uSy/ag=="
#          JWT_SECRET: "1d1bc524-3374-487a-bfc2-c362e1e3d3d1"
#          API_TOKEN_SALT: "7c7e1dc326e6486912d3e0aff6f96ccd"
